### ISSUE TITLE
Where do you find thetvdbapi?

### ISSUE THREAD

**Issue by bonelifer** [harvybob/missing_episodes#1]
Where do you find thetvdbapi? The one I found via google was from 2009 and the file no longer existed.

**Comment by harvybob** [comment]
I pinched it from here:

https://bitbucket.org/offbyone/mp4tagger/src/0fed48a20b10/lib/thetvdb/thetvdbapi.py?at=default&fileviewer=file-view-default

**Comment by harvybob** [comment]
I've added it to the report for use. Change API key as needed in the thetvdbapi.py file

**Comment by bonelifer** [comment]
Now only getting this error: NameError: global name 'logger' is not defined

**Comment by harvybob** [comment]
Ive updated the file. Location of error file also now needed.
Note that there is an eror in the details you have entered else you would not get to the logging part.

**Comment by bonelifer** [comment]
Getting somewhere. The problem was I had just put schema as "99", didn't realize I needed to put the full DBNAME.
It goes well, going through all my shows, then this:

Connecting to TVDB...
shows missing for: Waiting for God show number: 77998

Connecting to TVDB...
Traceback (most recent call last):
  File "missing_episodes.py", line 187, in <module>
    main()
  File "missing_episodes.py", line 166, in main
    get_tvdb_details_for_series_id(series_id)
  File "missing_episodes.py", line 77, in get_tvdb_details_for_series_id
    current_show_name = show_name.name
AttributeError: 'NoneType' object has no attribute 'name'

The log file is empty

**Comment by harvybob** [comment]
Ive just come across the same error when running for a show. investigating now.

**Comment by harvybob** [comment]
Not sure what is going on, it isn't an issue with my code as far as i can see, looks like tvdb isnt returning a name for that series. I have the issue with marvels: agents of shield. so its not limited to one particular program.

**Comment by bonelifer** [comment]
Your work is definitely appreciated. Was using the Missing Episodes plugin for MythTV, but he hadn't been on Google Code or responded to issues on the Github export of his code and it stopped working. I use a script for Filebot, but since it isn't the official script it could break if he updates the version of Groovy that Filebot uses and I'm not sure it's author is active anymore. His official script requires XATTR file metadata that I haven't been able to get working on my Linux box.

**Comment by harvybob** [comment]
Ive added a debug line at line 77, can you add that to your script, and run it again? Let me know what the last entry in the debug log is please?

**Comment by bonelifer** [comment]
2016-03-17 17:23:29,265 DEBUG root looking for 76648
2016-03-17 17:23:29,801 DEBUG root looking for 269613
2016-03-17 17:23:30,200 DEBUG root looking for 76321
2016-03-17 17:23:30,629 DEBUG root looking for 274897
2016-03-17 17:23:31,073 DEBUG root looking for 77505
2016-03-17 17:23:31,616 DEBUG root looking for 70584
2016-03-17 17:23:32,133 DEBUG root looking for 72173
2016-03-17 17:23:32,607 DEBUG root looking for 78572
2016-03-17 17:23:33,075 DEBUG root looking for 272135
2016-03-17 17:23:34,393 DEBUG root looking for 278125
2016-03-17 17:23:35,394 DEBUG root looking for 72614
2016-03-17 17:23:35,974 DEBUG root looking for 74337
2016-03-17 17:23:36,571 DEBUG root looking for 79173
2016-03-17 17:23:37,364 DEBUG root looking for 82459
2016-03-17 17:23:37,914 DEBUG root looking for 77998
2016-03-17 17:23:38,258 DEBUG root looking for 72108

**Comment by harvybob** [comment]
Intrestingly - your error came up with a show that works fine on my run - NCIS.

Not sure what is going on, but I have added a if statement to skip the name if it not coming back correctly so should run through the rest of the entries.

**Comment by harvybob** [comment]
This may be a glitch in the "thetvdbapi" code but will investigate more when i get a chance.

**Comment by bonelifer** [comment]
Might be a good idea to add a CFG file with the info and use .gitignore so it doesn't get uploaded to github. That way people can update without deleting and starting over.

**Comment by harvybob** [comment]
Will look into it when i get a chance - this was a little project for me to learn the basics in python!
Thought it would be useful for others hence i put it up.

**Comment by bonelifer** [comment]
Thanks.

**Comment by bonelifer** [comment]
Well, now it does this, will check back later:

william@william-mythtv:/var/tmp/missing_episodes$ python missing_episodes.py
  File "missing_episodes.py", line 80
    logging.debug("No name for "+series_id+" was returned)
                                                         ^
SyntaxError: EOL while scanning string literal

**Comment by harvybob** [comment]
Apologies, missed a " after the word returned and before the )

**Comment by harvybob** [comment]
Hi Bonelifer,

My episode that was failing before is now working -not that i have done anything... Please try again and see if yours runs through without error. Also I have setup cfg file processing, if you want to test!

**Comment by bonelifer** [comment]
Seems to work perfectly now. It even correctly got info for the original The Twilight Zone, which for some reason other TTVDB info scrappers usually try and get the 1985 version. Great work!

**Comment by harvybob** [comment]
In terms of incorrect versions, try helping the scraper by adding the year of interest in the folder name. Did you use the config version? Or the version from earlier in the week?

**Comment by bonelifer** [comment]
The new config version. It did work without the year.
