### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by bonelifer** [harvybob/missing_episodes#6]
Error on Kodi 17 mysql database.

> william@william-mythtv:/var/tmp/missing_episodes$ mser
Traceback (most recent call last):
  File "missing_episodes.py", line 240, in <module>
    main()
  File "missing_episodes.py", line 211, in main
    get_tvdb_details_for_series_id(series_id)
  File "missing_episodes.py", line 99, in get_tvdb_details_for_series_id
    for episode in show[1]:
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by harvybob** [comment]
Thanks for reporting, I got this error myself yesterday, kodi have changed their data layout, but I can't find the new layout so need to spend a bit of time working out what needs to change.

**Comment by harvybob** [comment]
Should be working now, i've also adjusted to show the series id for any duplicates.
